config/routes.rb
Rails.application.routes.draw do
  
  get 'password_resets/new'

  get 'password_resets/edit'

  root 		'static_pages#home'
  get  		'/help',    to: 'static_pages#help'
  get  		'/about',   to: 'static_pages#about'
  get  		'/contact', to: 'static_pages#contact'
  get     '/news',    to: 'static_pages#news'
  get  		'/signup',  to: 'users#new'
  get  		'/login', 	to: 'sessions#new'
  post 		'/login', 	to: 'sessions#create'
  delete  '/logout', 	to: 'sessions#destroy'

  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :microposts,          only: [:create, :destroy]
  resources :relationships,       only: [:create, :destroy]
end

app/views/shared/_carousel.html.erb
<div id="myCarousel" class="carousel slide" data-ride="carousel">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
    <li data-target="#myCarousel" data-slide-to="1"></li>
    <li data-target="#myCarousel" data-slide-to="2"></li>
    <li data-target="#myCarousel" data-slide-to="3"></li>
  </ol>

  <!-- Wrapper for slides -->
  <div class="carousel-inner" role="listbox">
    <div class="item active">
      <%= image_tag 'feature3.png' %>
      <div class="carousel-caption">
        Easy to use!
      </div>
    </div>
    <div class="item">
      <%= image_tag 'feature2.png' %>
      <div class="carousel-caption">
        Unlimited customisation options! Make your experience unique!
      </div>
    </div>
    <div class="item">
      <%= image_tag 'feature1.png' %>
      <div class="carousel-caption">
        Forgot your password? Don't worry, we've got you covered!
      </div>
    </div>
    <div class="item">
      <%= image_tag 'feature4.png' %>
      <div class="carousel-caption">
        Fancy messages!
      </div>
    </div>
  </div>

  <!-- Controls -->
  <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_experiences.html.erb
<div class="container2">
	<div class="row">
	  <div class="col-sm-6 col-md-12">
	    <div class="thumbnail">
	      <%= image_tag "vil.jpg" %>
	      <div class="caption", style="text-align: center;">
	        <h3>Vildana</h3>
	        <p>"cool4 [<i>sic</i>]"
	        (she didn't even look at it)</p>
	        <p><%= link_to "Register anyway!", signup_path, class: "btn btn-lg btn-primary" %></p>        
	      </div>
	    </div>
	  </div>
	</div>
	<div class="row">
	  <div class="col-sm-6 col-md-12">
	    <div class="thumbnail">
	      <%= image_tag "ana.jpg" %>
	      <div class="caption", style="text-align: center;">
	        <h3>Ana</h3>
	        <p>"Page is almost empty... Terrible!"</p>
	        <p><%= link_to "Meh, I'll give it a try!", signup_path, class: "btn btn-lg btn-primary" %></p>        
	      </div>
	    </div>
	  </div>
	</div>
	<div class="row">
	  <div class="col-sm-6 col-md-12">
	    <div class="thumbnail">
	      <%= image_tag "lam.jpg" %>
	      <div class="caption", style="text-align: center;">
	        <h3>Lamija</h3>
	        <p>"It says my mail is in use already..."</p>
	        <p><%= link_to "I have multiple mails, let me try it!", signup_path, class: "btn btn-lg btn-primary" %></p>        
	      </div>
	    </div>
	  </div>
	</div>
</div>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol class="microposts">
    <%= render @feed_items %>
  </ol>
  <%= will_paginate @feed_items %>
<% end %>

app/views/shared/_micropost_form.html.erb
<%= form_for(@micropost) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <%= f.text_area :content, placeholder: "Compose new micropost..." %>
  </div>
  <%= f.submit "Post", class: "btn btn-primary" %>
  <span class="picture">
    <%= f.file_field :picture, accept: 'image/jpeg,image/gif,image/png' %>
  </span>
<% end %>

<script type="text/javascript">
  $('#micropost_picture').bind('change', function() {
    var size_in_megabytes = this.files[0].size/1024/1024;
    if (size_in_megabytes > 5) {
      alert('Maximum file size is 5MB. Please choose a smaller file.');
    }
  });
</script>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <a href="<%= following_user_path(@user) %>">
    <strong id="following" class="stat">
      <%= @user.following.count %>
    </strong>
    following
  </a>
  <a href="<%= followers_user_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    followers
  </a>
</div>

app/views/shared/_user_info.html.erb
<%= link_to gravatar_for(current_user, size: 50), current_user %>
<h1><%= current_user.name %></h1>
<span><%= link_to "view my profile", current_user %></span>
<span><%= pluralize(current_user.microposts.count, "micropost") %></span>